1017/쇼핑몰_class/accounts/urls.py
from django.urls import path
from . import views

app_name ='accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),    
    #프로필 페이지: user_pk로 조회
    path('profile/<int:user_pk>/', views.profile, name='profile')
]

1017/쇼핑몰_class/shop/urls.py
from django.urls import path
from . import views

app_name ='shop'
urlpatterns = [
    path('', views.index, name='index'),
    path('cart/<int:product_pk>/', views.addcart, name="addcart"),
]

1017/쇼핑몰_class/shoppingmall/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),    
    path('accounts/', include('accounts.urls')),
]

1017/쇼핑몰_class/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    pass

1017/쇼핑몰_class/shop/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Product(models.Model):
    title = models.CharField(max_length=200)
    price = models.IntegerField()
    description = models.TextField()
    # 이미지 URL을 저장
    image = models.URLField()
    # 장바구니(product:user = M : N)
    # related_name : 역참조 시 사용할 이름
    users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='cart', blank=True)

1017/쇼핑몰_class/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()

class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        pass

1017/쇼핑몰_class/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm # 지금당장은 아이디/패스워드만 로그인하므로 커스텀안해도댐, 이메일로 로그인 기능넣으려면 커스텀
from .forms import CustomUserCreationForm, CustomUserChangeForm

# Create your views here.
# Todo : 회원가입 기능 구현 예정
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            # 회원가입
            user = form.save()
            # 로그인 후 리다이렉트
            auth_login(request, user)
            return redirect('shop:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form' : form
    }
    return render(request, 'accounts/signup.html', context)


# Todo : 로그인 기능 구현 예정
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('shop:index')
    else:
        form = AuthenticationForm()
    context = {
        'form' : form
    }
    return render(request, 'accounts/login.html', context)


# Todo : 로그아웃 기능 구현 예정
def logout(request):
    auth_logout(request)
    return redirect('shop:index')


# Todo : 프로필 기능 구현 예정
def profile(request):
    return render(request, 'accounts/profile.html')

1017/쇼핑몰_class/shop/views.py
from django.shortcuts import render, redirect
import requests
from .models import Product

# Create your views here.
def index(request):
    response = requests.get('https://fakestoreapi.com/products')
    products = response.json()

    # 반복하면서 저장
    for product in products:
        # 이미 DB에 저장된 상품이면 pass
        if Product.objects.filter(title=product['title']).exists():
            continue

        title = product['title']
        description = product['description']
        price = int(product['price'] * 1300)
        image = product['image']
        Product.objects.create(
            title=title,
            description=description,
            price=price,
            image=image
        )
    context = {
        'products': Product.objects.all(),
    }
    return render(request, 'shop/index.html', context)


def addcart(request, product_pk):
    product = Product.objects.get(id=product_pk)
    user = request.user

    # 이미 장바구니에 있는 상품이라면, 장바구니에서 제거
    if product in user.cart.all():
        user.cart.remove(product)

    # 없는 상품이라면 추가 
    else:
        user.cart.add(product)

    return redirect("shop:index")

1017/쇼핑몰_class/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<h1>로그인</h1>
<form action="{% url "accounts:login" %}" method = 'POST'>
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class='btn btn-primary'>로그인</button>
</form>

{% endblock content %}

1017/쇼핑몰_class/accounts/templates/accounts/profile.html
{% extends "base.html" %}


{% block content %}
<h1>{{ user }} 님의 페이지</h1>

<h3>장바구니에 담은 상품들</h3>

{% for product in user.cart.all %}
<p>{{ forloop.counter }} : {{ product.title }}</p>

<hr>
{% empty%}
<p>담긴 상품이 없습니다.</p>
{% endfor %}

{% endblock content %}

1017/쇼핑몰_class/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
<h1>회원가입</h1>
<form action="{% url "accounts:signup" %}" method = 'POST'>
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class='btn btn-primary'>회원가입</button>
</form>

{% endblock content %}

1017/쇼핑몰_class/shop/templates/shop/index.html
{% extends "base.html" %}

{% block content %}
  <h1>메인 페이지</h1>
  <div class="row">
  {% for product in products %}
  <div class="col-3 card">
    <img src="{{ product.image }}" class="card-img-top" alt="..." style="height: 300px;">
    <div class="card-body">
      <h5 class="card-title">{{ product.title }}</h5>
      <p class="card-text">{{ product.description|truncatechars:20 }}</p>
      <p class="cart-text">가격 : {{ product.price }}</p>
      {% if user.is_authenticated %}
        {% if product in user.cart.all %}
          <a href="{% url "shop:addcart" product.id %}">제외하기</a>
        {% else %}
          <a href="{% url "shop:addcart" product.id%}">장바구니에 담기</a>
        {% endif %}
      {% endif %}
    </div>
  </div>
  {% endfor %}
</div>
{% endblock content %}

1017/쇼핑몰_class/templates/_navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url "shop:index" %}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
      </ul>    
      <ul class="navbar-nav">
        <!-- 사용자가 로그인 한 경우-->
        {% if user.is_authenticated %}          
        <li class="nav-item">          
          <a class='nav-link' href="{% url "accounts:logout" %}">로그아웃</a>
        </li>
        {% else %}
        <li class="nav-item">          
          <a class='nav-link' href="{% url "accounts:login" %}">로그인</a>
        </li>
        <li class="nav-item">          
          <a class='nav-link' href="{% url "accounts:signup" %}">회원가입</a>
        </li>
          
        {% endif %}
      </ul>  
    </div>
  </div>
</nav>

1017/쇼핑몰_class/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
  {% include "_navbar.html" %}

  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>